/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.13.0.56.2 */
/* Module Version: 1.2 */
/* Fri May 24 15:59:59 2024 */

/* parameterized module instance */
SMBusFWUpdate __ (.wb_clk_i( ), .i2c1_scl( ), .i2c1_sda( ), 
    .i2c1_irqo( ));
