/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.13.0.56.2 */
/* Module Version: 5.7 */
/* Fri May 24 15:42:35 2024 */

/* parameterized module instance */
ExtPLL __ (.CLKI( ), .RST( ), .CLKOP( ), .CLKOS( ), .LOCK( ));
