/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.12.0.240.2 */
/* Module Version: 5.7 */
/* Tue Feb 08 15:43:00 2022 */

/* parameterized module instance */
SYS_PLL __ (.CLKI( ), .RST( ), .CLKOP( ), .CLKOS( ), .LOCK( ));
