/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.13.0.56.2 */
/* Module Version: 1.2 */
/* Mon Oct 14 11:54:08 2024 */

/* parameterized module instance */
EFB_UFM __ (.wb_clk_i( ), .wb_rst_i( ), .wb_cyc_i( ), .wb_stb_i( ), 
    .wb_we_i( ), .wb_adr_i( ), .wb_dat_i( ), .wb_dat_o( ), .wb_ack_o( ), 
    .i2c1_scl( ), .i2c1_sda( ), .i2c1_irqo( ), .wbc_ufm_irq( ));
