/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.12.1.454 */
/* Module Version: 1.2 */
/* Thu Feb 17 13:52:34 2022 */

/* parameterized module instance */
I2C_Update __ (.wb_clk_i( ), .i2c1_scl( ), .i2c1_sda( ), .i2c1_irqo( ));
